services:
  postgres:
    image: postgres:15-alpine
    container_name: alphastream_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: alphastream
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: alphastream_cache
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata:
